version: '3.3'
services:
    bob:
        image: nginx
        container_name: bob
        ports:
            - "11443:443"
        volumes:
            - ./nginx/bob.html:/usr/share/nginx/html/index.html
            - ./nginx/bob.conf:/etc/nginx/conf.d/default.conf
            - ../temp/trustable-tom/trustable-tom.crt:/etc/ssl/certs/nginx/trustable-tom.crt
            - ../temp/bob/bob.crt:/etc/ssl/certs/nginx/bob.crt
            - ../temp/bob/bob.key:/etc/ssl/certs/nginx/bob.key
